package com.briup.crm.dao;

import com.briup.crm.bean.SalChance;
import com.briup.crm.bean.SalChanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalChanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    long countByExample(SalChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int deleteByExample(SalChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int deleteByPrimaryKey(Long chcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int insert(SalChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int insertSelective(SalChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    List<SalChance> selectByExample(SalChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    SalChance selectByPrimaryKey(Long chcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalChance record, @Param("example") SalChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByExample(@Param("record") SalChance record, @Param("example") SalChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByPrimaryKeySelective(SalChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_chance
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByPrimaryKey(SalChance record);
}