package com.briup.crm.dao;

import com.briup.crm.bean.SalPlan;
import com.briup.crm.bean.SalPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    long countByExample(SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int deleteByExample(SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int deleteByPrimaryKey(Long plaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int insert(SalPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int insertSelective(SalPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    List<SalPlan> selectByExample(SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    SalPlan selectByPrimaryKey(Long plaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalPlan record, @Param("example") SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByExample(@Param("record") SalPlan record, @Param("example") SalPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByPrimaryKeySelective(SalPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Dec 31 17:29:45 CST 2019
     */
    int updateByPrimaryKey(SalPlan record);
}